# Generated by Django 4.1.3 on 2022-12-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_adress_alter_customuser_email_and_more'),
        ('users', '0004_alter_customuser_adress_alter_customuser_email_and_more'),
    ]

    operations = [
    ]
